Move all DB queries to Transactions withing Context
minio/m3 pull request #243
Opened 2019-12-28 20:29 UTC by dvaldivia

**Big change, need a lot of eyes**

With the current approach to managing database connections we are opening a db connection per tenant, this means that at any given point if we have `n` tenants we have `1+n` connections on any instance of m3 (m3, scheduler or a task) this quickly overruns the max number of connections supported by a regular postgres (100 on a 4GB ram instance)

To fix this we are moving to a connection model, similar to Django, where all the operations always happen within  a transaction, and the transaction is started at the begining of the request, since we already have the `cluster.Context` and we already keep transactions there, I just moved all non-transacitonal queries to use ctx transactions.

More over, the transactions are started when the context is started.

`db.GetInstance().Db` is deprecated and should be avoided

2019-12-30 03:15 UTC, cesnietor commented
this happens right after running setup on kind cluster:
```
2019/12/30 01:58:24 pq: CREATE DATABASE cannot run inside a transaction block
2019/12/30 01:58:24 error connecting to database or reading migrations
2019/12/30 01:58:24 sql: Scan error on column index 0, name "current_schema": converting NULL to string is unsupported in line 0: SELECT CURRENT_SCHEMA()
2019/12/30 01:58:24 Adding the first admin
2019/12/30 01:58:26 Error adding user: pq: relation "admins" does not exist
2019/12/30 01:58:26 Could not store global bucket configuration. pq: current transaction is aborted, commands ignored until end of transaction block
2019/12/30 01:58:26 pq: current transaction is aborted, commands ignored until end of transaction block
2019/12/30 01:58:26 Starting m3 services...
2019/12/30 01:58:26 missing config
2019/12/30 01:58:26 pq: relation "configurations" does not exist
```

2019-12-30 06:50 UTC, cesnietor commented
when I try to login with two different users on the same tenant I get:
```
v2019/12/30 06:50:27 /m3.PublicAPI/Login
2019/12/30 06:50:27 pq: sorry, too many clients already
```

2020-01-02 14:40 UTC, nitisht commented on api/api-private-tenant-permissions.go
> +		return nil, status.New(codes.Internal, "Internal error 1").Err()
This should be just "Internal Error" AFAICS

2020-01-02 14:40 UTC, nitisht commented on api/api-private-tenant-permissions.go
> +		return nil, status.New(codes.Internal, "Internal error 2").Err()
This should be just "Internal Error" AFAICS

2020-01-02 17:29 UTC, nitisht requested changes
few comments

2020-01-02 17:29 UTC, nitisht commented on api/api-private-tenant.go
> +		//}
can we remove the commented code

2020-01-02 17:29 UTC, nitisht commented on api/api-public-authentication-grpc.go
> +	//}
this can be removed as well

2020-01-02 17:29 UTC, nitisht commented on api/api-public-tenant-permissions.go
>  	// get permission
No rollback now?

2020-01-03 01:20 UTC, closed without merging