Version Public API
minio/m3 pull request #308
Opened 2020-01-29 19:47 UTC by dvaldivia

Adds an API to check the m3 version at `/api/v1/version` this returns whatever was set at compilation time.

For docker, this is either the current tag being built or the current git tag

2020-01-30 20:07 UTC, Alevsk submitted a review, later dismissed

2020-01-30 21:38 UTC, cesnietor requested changes

2020-01-30 21:38 UTC, cesnietor commented on version/version.go
> +// along with this program.  If not, see <http://www.gnu.org/licenses/>.
```suggestion
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

```

2020-01-31 00:20 UTC, Alevsk approved these changes

2020-01-31 00:22 UTC, cesnietor approved these changes

2020-01-31 00:22 UTC, merged