Rename Clusters to Tenants
minio/m3 pull request #398
Opened 2020-06-01 19:12 UTC by dvaldivia

2020-06-01 19:35 UTC, cesnietor requested changes
please remove all .orig files

2020-06-01 19:35 UTC, cesnietor commented on restapi/configure_m3.go.orig
> +
remove this file

2020-06-01 20:39 UTC, dvaldivia commented on restapi/configure_m3.go.orig
> +
done

2020-06-01 22:40 UTC, Alevsk submitted a review, later dismissed

2020-06-01 22:49 UTC, cesnietor requested changes
you also need to delete all the operations/admin_api cluster related files and the models/...cluster...* related files since those are not deleted on swagger generation.

2020-06-02 16:28 UTC, dvaldivia commented
@cesnietor done

2020-06-02 17:52 UTC, cesnietor commented on restapi/tenants.go
> +
this seems not part of this PR

2020-06-02 18:16 UTC, cesnietor approved these changes
LGTM

2020-06-02 18:22 UTC, merged