Service account authentication for Mkube
minio/m3 pull request #407
Opened 2020-06-09 06:19 UTC by Alevsk

Currently, Mkube support only bearer token authentication for secured endpoints,
clients that wishes to access resources behind a secured endpoint will need to provide
a jwt token using the HTTP `Authorization` header, ie:

```
curl --location --request GET 'http://localhost:8787/api/v1/tenants' --header 'Authorization: Bearer eyJ...'
```

The provided `JWT token` corresponds to the `Kubernetes service account` that Mkube will use to run tasks on behalf of the client
ie: list, create, edit, delete tenants, etc.

For local development you can use the jwt associated to the `m3-sa` service account, you can get the token running
the following command in your terminal:

```
kubectl get secret $(kubectl get serviceaccount m3-sa -o jsonpath="{.secrets[0].name}") -o jsonpath="{.data.token}" | base64 --decode
```
Then test the token works with `curl`
```
curl --location --request GET 'http://localhost:8787/api/v1/tenants' --header 'Authorization: Bearer eyJ...'
...
{
    "tenants": [
        {
            "creation_date": "2020-06-08 22:35:50 -0700 PDT",
            "currentState": "Ready",
            "instance_count": 4,
            "name": "minio",
            "volume_count": 16,
            "volume_size": 1099511627776,
            "zone_count": 1
        }
    ]
}
```

2020-06-09 18:28 UTC, dvaldivia commented on m3.yaml
>                    type: string
this file is no more, it's not in the kustomize files

2020-06-09 18:30 UTC, cesnietor requested changes
could you please remove all related models/ that are not used anymore and also the operations/user_api since those files are not deleted by swagger generator

2020-06-09 18:48 UTC, dvaldivia requested changes

2020-06-09 18:48 UTC, dvaldivia commented on go.mod
> +	k8s.io/klog v1.0.0
we dont' need klog do we?

2020-06-09 22:09 UTC, dvaldivia submitted a review, later dismissed

2020-06-15 21:17 UTC, cesnietor approved these changes

2020-06-15 21:23 UTC, merged